# ~/.config/hypr/hypridle.conf

general {
    # IMPORTANTE: Llamamos a tu script en lugar de hyprlock directamente
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && waybar &
}
}

# (Opcional) Oscurecer la pantalla tras 3 minutos
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# BLOQUEAR PANTALLA: Se activa tras 5 minutos
listener {
    timeout = 300
    # Al disparar lock-session, Hyprland ejecuta el lock_cmd definido arriba
    on-timeout = loginctl lock-session
}

# Apagar monitor tras 5.5 minutos
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
