foreground              #FFFFFF
background              #000104
selection_foreground    #000104
selection_background    #FFFFFF
cursor                  #4D67C4 
cursor_text_color       #E0E0DD

active_tab_foreground     #000104
active_tab_background     #253588
inactive_tab_foreground   #253588
inactive_tab_background   #000104

# black
color0      #293352
color8      #57658F

# red
color1      #CCD7FF
color9      #AAB9F0

# green
color2      #CCD3FF
color10     #AAB3F0

# yellow
color3      #CCD4FF
color11     #AAB5F0

# blue
color4      #9AADE6
color12     #9AADE6

# magenta
color5      #9AA4E6
color13     #9AA4E6

# cyan
color6      #9AA6E6
color14     #9AA6E6

# white
color7      #CCD7FF
color15     #AAB9F0
